title: Bem-vindo ao meu blog.
description: > # this means to ignore newlines until "baseurl:"
  Aqui compartilho conhecimento sobre as tecnologias que aprendi.
permalink: ":title/"
baseurl: "/lsm-5.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Lucas Mendonça # add your name
author-img: lucas-mendonca.jpg # add your photo
about-author: Sou estudante em Ciências da Computação e estagiário em front-end na Praecanto Tecnologia. # add description
social-github: lsm-5 # add your Github handle
social-linkedin: lucas-mendonça-12181a187 # add your Linkedin handle
social-email: Lucas Mendonca <lsm5@cin.ufpe.br> # add your Email address

# Disqus
discus-identifier: mr-mendonça # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
